### ISSUE TITLE
zellij is very slow

### ISSUE THREAD

**Issue by fansari** [zellij-org/zellij#443]
I have built and tested zellij 0.6.0 on VMs running on Proxmox Hypervisor and ApacheCloud Stack ("cargo install zellij").

In both cases zellij is very slow. Even  when just typing within bash feels like using an analog modem dialup.

I added CPU and RAM to the Proxmox VM (4x CPU, 8 GB RAM) but this did not help.

This means currently this is not usable.

Tested with Fedora CoreOS 33 and CentOS Stream 8.

**Comment by a-kenji** [comment]
Hello, thank you for taking the time writing this issue!

Can you please add the terminal emulator, that you were using?
It could have a large impact on performance, that said there are a few attempts at improving performance at the moment.

**Comment by fansari** [comment]
I am running SecureCRT 9.0.1.

**Comment by ms-jpq** [comment]
I can attest to this on iTerm2, the speed is very slow, especially when I opened neovim, it was basically unusable.

:(

**Comment by saintphaenixos** [comment]
I can confirm with @ms-jpq that Zellij runs quite slowly on MacOS 10.15.7 Catalina.

It's not unusable, but its close to that.

**Comment by imsnif** [comment]
The main performance bottlenecks Zellij has right now (that I'm aware of) are in writing to stdout. We're working on addressing those in an open PR. Meanwhile, if you use a gpu accelerated terminal (eg. Alacritty or urxvt) performance should be greatly improved (on my machine it's indistinguishable from a normal terminal).

**Comment by kchen0x** [comment]
When scrolling my pane in Zellij with macOS 11/iTerm 2, the CPU usage arises from 15%(idle) to almost 80%.

**Comment by PSeitz** [comment]
For me scrolling in nvim is really slow with Alacritty. Tested with 0.12.1

**Comment by imsnif** [comment]
@PSeitz - I have heard this before and think it deserves its own issue. Since I cannot reproduce this myself, would you be willing to open a separate issue and follow the bug reporting instructions (including attaching the files)? That way I would be able to see exactly what's wrong and fix it.

@kchen0x and others - the CPU utilization issue is solved in main and I'm currently working on improving our render performance, so hopefully the next version should have some significant improvements in this regard.

**Comment by imsnif** [comment]
This issue is very much solved in `0.13.0` - Zellij rendering performance is now on par with tmux. If anyone is still experiencing slowness issues, they are likely particular to a specific scenario. In that case, please open a new issue and attach logs as instructed so that we can debug and fix them.

**Comment by vivekascoder** [comment]
> you please add the terminal emulator, that you were using?
> It could have a large impact on performa

This is still arising on `0.31.4`. There is just too much latency to work and it's not arising while using tmux.

**Comment by inferiorhumanorgans** [comment]
Yep. Still an issue in 0.38.2 w/ iTerm 3.4.15 and helix 23.05.  Scrolling is painfully slow.

**Comment by imsnif** [comment]
Friends - this is an old issue that wasn't descriptive enough to begin with. If you have a reproducer or a gif, please open a new issue with it. Commenting or reacting here won't help us solve anything.
